-- assets : 资源列表
-- 字段定义
local fields = {
    id = 1, -- 主键
    bundle = 2, -- bundle名字
    asset = 3, -- 资产命名
    type = 4, -- 资产类型
}

local cfgMgr = require("Config.cfgMgr")

-- ref
local refs = {
}

-- 所有原始数据
local assets = {}

local cache = {}

local datas = {
    { "Packages/com.oasis.unity.audio/Gizmos/AudioItem Icon.png", "foundation", "AudioItem Icon", ".png" },
    { "Assets/Game/I18N/CatalogTable.asset", "i18n/catalogtable", "CatalogTable", ".asset" },
    { "Assets/Game/I18N/en.mo.bytes", "i18n/en.mo", "en.mo", ".bytes" },
    { "Assets/Game/I18N/zh_Hant.mo.bytes", "i18n/zh_hant.mo", "zh_Hant.mo", ".bytes" },
    { "Assets/Game/LuaBundle/Channel/AuthModel.lua.bytes", "lua/channel", "AuthModel.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Channel/ChannelAgent.lua.bytes", "lua/channel", "ChannelAgent.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Channel/Default/ChannelAgent.lua.bytes", "lua/channel", "ChannelAgent.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Channel/Default/LoginAgentView.lua.bytes", "lua/channel", "LoginAgentView.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Const/AnimatorID.lua.bytes", "lua/const", "AnimatorID.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/AppEvents.lua.bytes", "lua/foundation", "AppEvents.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/BaseClass.lua.bytes", "lua/foundation", "BaseClass.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/BindGroup.lua.bytes", "lua/foundation", "BindGroup.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/CoroutinePool.lua.bytes", "lua/foundation", "CoroutinePool.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/Event.lua.bytes", "lua/foundation", "Event.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/IsNil.lua.bytes", "lua/foundation", "IsNil.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/List.lua.bytes", "lua/foundation", "List.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/ModelReducer.lua.bytes", "lua/foundation", "ModelReducer.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/ModelText.lua.bytes", "lua/foundation", "ModelText.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/ModelValue.lua.bytes", "lua/foundation", "ModelValue.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/Promise.lua.bytes", "lua/foundation", "Promise.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/SimpleClass.lua.bytes", "lua/foundation", "SimpleClass.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/U3DObject.lua.bytes", "lua/foundation", "U3DObject.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/Window.lua.bytes", "lua/foundation", "Window.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/WindowHandle.lua.bytes", "lua/foundation", "WindowHandle.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/WindowLayer.lua.bytes", "lua/foundation", "WindowLayer.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Core/WindowManager.lua.bytes", "lua/foundation", "WindowManager.lua", ".bytes" },
    { "Assets/Game/LuaBundle/LuaDebug.lua.bytes", "lua/foundation", "LuaDebug.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Main.lua.bytes", "lua/foundation", "Main.lua", ".bytes" },
    { "Assets/Game/LuaBundle/xlua/util.lua.bytes", "lua/foundation", "util.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/Ctrl/LaunchCtrl.lua.bytes", "lua/game/ctrl", "LaunchCtrl.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/Ctrl/LoginCtrl.lua.bytes", "lua/game/ctrl", "LoginCtrl.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/Ctrl/PreloadCtrl.lua.bytes", "lua/game/ctrl", "PreloadCtrl.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/Ctrl/SettingCtrl.lua.bytes", "lua/game/ctrl", "SettingCtrl.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/Ctrl/UpdateAssetConfig.lua.bytes", "lua/game/ctrl", "UpdateAssetConfig.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/Ctrl/UpdateAssetCtrl.lua.bytes", "lua/game/ctrl", "UpdateAssetCtrl.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/Ctrl/WorldCtrl.lua.bytes", "lua/game/ctrl", "WorldCtrl.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/Model/LaunchModel.lua.bytes", "lua/game/model", "LaunchModel.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/Model/LoginModel.lua.bytes", "lua/game/model", "LoginModel.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/Model/ZoneGroupModel.lua.bytes", "lua/game/model", "ZoneGroupModel.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/Model/ZoneItemModel.lua.bytes", "lua/game/model", "ZoneItemModel.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/View/JoystickView.lua.bytes", "lua/game/view", "JoystickView.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/View/LoginView.lua.bytes", "lua/game/view", "LoginView.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/View/MainView.lua.bytes", "lua/game/view", "MainView.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/View/SettingView.lua.bytes", "lua/game/view", "SettingView.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/View/ZoneGroupItemView.lua.bytes", "lua/game/view", "ZoneGroupItemView.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/View/ZoneItemView.lua.bytes", "lua/game/view", "ZoneItemView.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Game/View/ZoneView.lua.bytes", "lua/game/view", "ZoneView.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/AudioManager.lua.bytes", "lua/tool", "AudioManager.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/I18NManager.lua.bytes", "lua/tool", "I18NManager.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/Loading/Loading.lua.bytes", "lua/tool", "Loading.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/Loading/LoadingConfig.lua.bytes", "lua/tool", "LoadingConfig.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/Loading/LoadingModel.lua.bytes", "lua/tool", "LoadingModel.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/Loading/LoadingView.lua.bytes", "lua/tool", "LoadingView.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/LoadingTips/LoadingTips.lua.bytes", "lua/tool", "LoadingTips.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/LoadingTips/LoadingTipsModel.lua.bytes", "lua/tool", "LoadingTipsModel.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/LoadingTips/LoadingTipsView.lua.bytes", "lua/tool", "LoadingTipsView.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/MessageBox/MessageBox.lua.bytes", "lua/tool", "MessageBox.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/MessageBox/MessageBoxModel.lua.bytes", "lua/tool", "MessageBoxModel.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/MessageBox/MessageBoxView.lua.bytes", "lua/tool", "MessageBoxView.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/Quality.lua.bytes", "lua/tool", "Quality.lua", ".bytes" },
    { "Assets/Game/LuaBundle/Tool/Splash.lua.bytes", "lua/tool", "Splash.lua", ".bytes" },
    { "Assets/Game/Misc/GameRoot/GameRoot.prefab", "misc/gameroot", "GameRoot", ".prefab" },
    { "Assets/Game/Misc/Input/Control.inputactions", "misc/input", "Control", ".inputactions" },
    { "Assets/Game/Misc/QualityConfig/LWRP_Balance.asset", "misc/qualityconfig", "LWRP_Balance", ".asset" },
    { "Assets/Game/Misc/QualityConfig/LWRP_Fast.asset", "misc/qualityconfig", "LWRP_Fast", ".asset" },
    { "Assets/Game/Misc/QualityConfig/LWRP_Perfect.asset", "misc/qualityconfig", "LWRP_Perfect", ".asset" },
    { "Assets/Game/Misc/QualityConfig/QualityConfig.asset", "misc/qualityconfig", "QualityConfig", ".asset" },
    { "Assets/Game/Content/Materials/BlueDragon/bluemat.mat", "prefab/bluedragon", "bluemat", ".mat" },
    { "Assets/Game/Content/Prefab/BlueDragon/BlueDragon.prefab", "prefab/bluedragon", "BlueDragon", ".prefab" },
    { "Assets/Game/Content/Texture/BlueDragon/sdfa.png", "prefab/bluedragon", "sdfa", ".png" },
    { "Assets/Game/Content/Animations/Dragon/Basic Attack.anim", "prefab/dragon", "Basic Attack", ".anim" },
    { "Assets/Game/Content/Animations/Dragon/Claw Attack.anim", "prefab/dragon", "Claw Attack", ".anim" },
    { "Assets/Game/Content/Animations/Dragon/Defend.anim", "prefab/dragon", "Defend", ".anim" },
    { "Assets/Game/Content/Animations/Dragon/Die.anim", "prefab/dragon", "Die", ".anim" },
    { "Assets/Game/Content/Animations/Dragon/Flame Attack.anim", "prefab/dragon", "Flame Attack", ".anim" },
    { "Assets/Game/Content/Animations/Dragon/Fly Flame Attack 1.anim", "prefab/dragon", "Fly Flame Attack 1", ".anim" },
    { "Assets/Game/Content/Animations/Dragon/Fly Flame Attack.anim", "prefab/dragon", "Fly Flame Attack", ".anim" },
    { "Assets/Game/Content/Animations/Dragon/Fly Forward.anim", "prefab/dragon", "Fly Forward", ".anim" },
    { "Assets/Game/Content/Animators/Dragon/Dragon.controller", "prefab/dragon", "Dragon", ".controller" },
    { "Assets/Game/Content/Model/Dragon/Dragon.fbx", "prefab/dragon", "Dragon", ".fbx" },
    { "Assets/Game/Content/Animations/Knight/WK_heavy_infantry_04_charge.FBX", "prefab/knight", "WK_heavy_infantry_04_charge", ".FBX" },
    { "Assets/Game/Content/Animations/Knight/WK_heavy_infantry_05_combat_idle.FBX", "prefab/knight", "WK_heavy_infantry_05_combat_idle", ".FBX" },
    { "Assets/Game/Content/Animations/Knight/WK_heavy_infantry_06_combat_walk.FBX", "prefab/knight", "WK_heavy_infantry_06_combat_walk", ".FBX" },
    { "Assets/Game/Content/Animations/Knight/WK_heavy_infantry_08_attack_B.FBX", "prefab/knight", "WK_heavy_infantry_08_attack_B", ".FBX" },
    { "Assets/Game/Content/Animators/Knight/knight_animator.controller", "prefab/knight", "knight_animator", ".controller" },
    { "Assets/Game/Content/Materials/Knight/DemoTexture.mat", "prefab/knight", "DemoTexture", ".mat" },
    { "Assets/Game/Content/Model/Knight/ToonRTS_demo_Knight_mesh.FBX", "prefab/knight", "ToonRTS_demo_Knight_mesh", ".FBX" },
    { "Assets/Game/Content/Prefab/Knight/ToonRTS_demo_Knight.prefab", "prefab/knight", "ToonRTS_demo_Knight", ".prefab" },
    { "Assets/Game/Content/Texture/Knight/DemoTexture.png", "prefab/knight", "DemoTexture", ".png" },
    { "Assets/Game/Content/Materials/RedDragon/red.mat", "prefab/reddragon", "red", ".mat" },
    { "Assets/Game/Content/Prefab/RedDragon/RedDragon.prefab", "prefab/reddragon", "RedDragon", ".prefab" },
    { "Assets/Game/Content/Texture/RedDragon/redhr.png", "prefab/reddragon", "redhr", ".png" },
    { "Assets/Game/Content/Effects/Shader/add.shader", "prefab/shader", "add", ".shader" },
    { "Assets/Game/Content/Effects/Shader/blend.shader", "prefab/shader", "blend", ".shader" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_0.unity", "scenebasics/scene_basic_0_0", "Scene_Basic_0_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_1.unity", "scenebasics/scene_basic_0_1", "Scene_Basic_0_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_2.unity", "scenebasics/scene_basic_0_2", "Scene_Basic_0_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_3.unity", "scenebasics/scene_basic_0_3", "Scene_Basic_0_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_4.unity", "scenebasics/scene_basic_0_4", "Scene_Basic_0_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_5.unity", "scenebasics/scene_basic_0_5", "Scene_Basic_0_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_6.unity", "scenebasics/scene_basic_0_6", "Scene_Basic_0_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_7.unity", "scenebasics/scene_basic_0_7", "Scene_Basic_0_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_8.unity", "scenebasics/scene_basic_0_8", "Scene_Basic_0_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_9.unity", "scenebasics/scene_basic_0_9", "Scene_Basic_0_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_10.unity", "scenebasics/scene_basic_0_10", "Scene_Basic_0_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_11.unity", "scenebasics/scene_basic_0_11", "Scene_Basic_0_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_12.unity", "scenebasics/scene_basic_0_12", "Scene_Basic_0_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_13.unity", "scenebasics/scene_basic_0_13", "Scene_Basic_0_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_14.unity", "scenebasics/scene_basic_0_14", "Scene_Basic_0_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_15.unity", "scenebasics/scene_basic_0_15", "Scene_Basic_0_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_16.unity", "scenebasics/scene_basic_0_16", "Scene_Basic_0_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_0_17.unity", "scenebasics/scene_basic_0_17", "Scene_Basic_0_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_0.unity", "scenebasics/scene_basic_1_0", "Scene_Basic_1_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_1.unity", "scenebasics/scene_basic_1_1", "Scene_Basic_1_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_2.unity", "scenebasics/scene_basic_1_2", "Scene_Basic_1_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_3.unity", "scenebasics/scene_basic_1_3", "Scene_Basic_1_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_4.unity", "scenebasics/scene_basic_1_4", "Scene_Basic_1_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_5.unity", "scenebasics/scene_basic_1_5", "Scene_Basic_1_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_6.unity", "scenebasics/scene_basic_1_6", "Scene_Basic_1_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_7.unity", "scenebasics/scene_basic_1_7", "Scene_Basic_1_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_8.unity", "scenebasics/scene_basic_1_8", "Scene_Basic_1_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_9.unity", "scenebasics/scene_basic_1_9", "Scene_Basic_1_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_10.unity", "scenebasics/scene_basic_1_10", "Scene_Basic_1_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_11.unity", "scenebasics/scene_basic_1_11", "Scene_Basic_1_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_12.unity", "scenebasics/scene_basic_1_12", "Scene_Basic_1_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_13.unity", "scenebasics/scene_basic_1_13", "Scene_Basic_1_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_14.unity", "scenebasics/scene_basic_1_14", "Scene_Basic_1_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_15.unity", "scenebasics/scene_basic_1_15", "Scene_Basic_1_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_16.unity", "scenebasics/scene_basic_1_16", "Scene_Basic_1_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_1_17.unity", "scenebasics/scene_basic_1_17", "Scene_Basic_1_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_0.unity", "scenebasics/scene_basic_2_0", "Scene_Basic_2_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_1.unity", "scenebasics/scene_basic_2_1", "Scene_Basic_2_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_2.unity", "scenebasics/scene_basic_2_2", "Scene_Basic_2_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_3.unity", "scenebasics/scene_basic_2_3", "Scene_Basic_2_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_4.unity", "scenebasics/scene_basic_2_4", "Scene_Basic_2_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_5.unity", "scenebasics/scene_basic_2_5", "Scene_Basic_2_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_6.unity", "scenebasics/scene_basic_2_6", "Scene_Basic_2_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_7.unity", "scenebasics/scene_basic_2_7", "Scene_Basic_2_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_8.unity", "scenebasics/scene_basic_2_8", "Scene_Basic_2_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_9.unity", "scenebasics/scene_basic_2_9", "Scene_Basic_2_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_10.unity", "scenebasics/scene_basic_2_10", "Scene_Basic_2_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_11.unity", "scenebasics/scene_basic_2_11", "Scene_Basic_2_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_12.unity", "scenebasics/scene_basic_2_12", "Scene_Basic_2_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_13.unity", "scenebasics/scene_basic_2_13", "Scene_Basic_2_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_14.unity", "scenebasics/scene_basic_2_14", "Scene_Basic_2_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_15.unity", "scenebasics/scene_basic_2_15", "Scene_Basic_2_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_16.unity", "scenebasics/scene_basic_2_16", "Scene_Basic_2_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_2_17.unity", "scenebasics/scene_basic_2_17", "Scene_Basic_2_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_0.unity", "scenebasics/scene_basic_3_0", "Scene_Basic_3_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_1.unity", "scenebasics/scene_basic_3_1", "Scene_Basic_3_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_2.unity", "scenebasics/scene_basic_3_2", "Scene_Basic_3_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_3.unity", "scenebasics/scene_basic_3_3", "Scene_Basic_3_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_4.unity", "scenebasics/scene_basic_3_4", "Scene_Basic_3_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_5.unity", "scenebasics/scene_basic_3_5", "Scene_Basic_3_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_6.unity", "scenebasics/scene_basic_3_6", "Scene_Basic_3_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_7.unity", "scenebasics/scene_basic_3_7", "Scene_Basic_3_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_8.unity", "scenebasics/scene_basic_3_8", "Scene_Basic_3_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_9.unity", "scenebasics/scene_basic_3_9", "Scene_Basic_3_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_10.unity", "scenebasics/scene_basic_3_10", "Scene_Basic_3_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_11.unity", "scenebasics/scene_basic_3_11", "Scene_Basic_3_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_12.unity", "scenebasics/scene_basic_3_12", "Scene_Basic_3_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_13.unity", "scenebasics/scene_basic_3_13", "Scene_Basic_3_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_14.unity", "scenebasics/scene_basic_3_14", "Scene_Basic_3_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_15.unity", "scenebasics/scene_basic_3_15", "Scene_Basic_3_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_16.unity", "scenebasics/scene_basic_3_16", "Scene_Basic_3_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_3_17.unity", "scenebasics/scene_basic_3_17", "Scene_Basic_3_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_0.unity", "scenebasics/scene_basic_4_0", "Scene_Basic_4_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_1.unity", "scenebasics/scene_basic_4_1", "Scene_Basic_4_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_2.unity", "scenebasics/scene_basic_4_2", "Scene_Basic_4_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_3.unity", "scenebasics/scene_basic_4_3", "Scene_Basic_4_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_4.unity", "scenebasics/scene_basic_4_4", "Scene_Basic_4_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_5.unity", "scenebasics/scene_basic_4_5", "Scene_Basic_4_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_6.unity", "scenebasics/scene_basic_4_6", "Scene_Basic_4_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_7.unity", "scenebasics/scene_basic_4_7", "Scene_Basic_4_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_8.unity", "scenebasics/scene_basic_4_8", "Scene_Basic_4_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_9.unity", "scenebasics/scene_basic_4_9", "Scene_Basic_4_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_10.unity", "scenebasics/scene_basic_4_10", "Scene_Basic_4_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_11.unity", "scenebasics/scene_basic_4_11", "Scene_Basic_4_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_12.unity", "scenebasics/scene_basic_4_12", "Scene_Basic_4_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_13.unity", "scenebasics/scene_basic_4_13", "Scene_Basic_4_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_14.unity", "scenebasics/scene_basic_4_14", "Scene_Basic_4_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_15.unity", "scenebasics/scene_basic_4_15", "Scene_Basic_4_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_16.unity", "scenebasics/scene_basic_4_16", "Scene_Basic_4_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_4_17.unity", "scenebasics/scene_basic_4_17", "Scene_Basic_4_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_0.unity", "scenebasics/scene_basic_5_0", "Scene_Basic_5_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_1.unity", "scenebasics/scene_basic_5_1", "Scene_Basic_5_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_2.unity", "scenebasics/scene_basic_5_2", "Scene_Basic_5_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_3.unity", "scenebasics/scene_basic_5_3", "Scene_Basic_5_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_4.unity", "scenebasics/scene_basic_5_4", "Scene_Basic_5_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_5.unity", "scenebasics/scene_basic_5_5", "Scene_Basic_5_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_6.unity", "scenebasics/scene_basic_5_6", "Scene_Basic_5_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_7.unity", "scenebasics/scene_basic_5_7", "Scene_Basic_5_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_8.unity", "scenebasics/scene_basic_5_8", "Scene_Basic_5_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_9.unity", "scenebasics/scene_basic_5_9", "Scene_Basic_5_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_10.unity", "scenebasics/scene_basic_5_10", "Scene_Basic_5_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_11.unity", "scenebasics/scene_basic_5_11", "Scene_Basic_5_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_12.unity", "scenebasics/scene_basic_5_12", "Scene_Basic_5_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_13.unity", "scenebasics/scene_basic_5_13", "Scene_Basic_5_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_14.unity", "scenebasics/scene_basic_5_14", "Scene_Basic_5_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_15.unity", "scenebasics/scene_basic_5_15", "Scene_Basic_5_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_16.unity", "scenebasics/scene_basic_5_16", "Scene_Basic_5_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_5_17.unity", "scenebasics/scene_basic_5_17", "Scene_Basic_5_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_0.unity", "scenebasics/scene_basic_6_0", "Scene_Basic_6_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_1.unity", "scenebasics/scene_basic_6_1", "Scene_Basic_6_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_2.unity", "scenebasics/scene_basic_6_2", "Scene_Basic_6_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_3.unity", "scenebasics/scene_basic_6_3", "Scene_Basic_6_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_4.unity", "scenebasics/scene_basic_6_4", "Scene_Basic_6_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_5.unity", "scenebasics/scene_basic_6_5", "Scene_Basic_6_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_6.unity", "scenebasics/scene_basic_6_6", "Scene_Basic_6_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_7.unity", "scenebasics/scene_basic_6_7", "Scene_Basic_6_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_8.unity", "scenebasics/scene_basic_6_8", "Scene_Basic_6_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_9.unity", "scenebasics/scene_basic_6_9", "Scene_Basic_6_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_10.unity", "scenebasics/scene_basic_6_10", "Scene_Basic_6_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_11.unity", "scenebasics/scene_basic_6_11", "Scene_Basic_6_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_12.unity", "scenebasics/scene_basic_6_12", "Scene_Basic_6_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_13.unity", "scenebasics/scene_basic_6_13", "Scene_Basic_6_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_14.unity", "scenebasics/scene_basic_6_14", "Scene_Basic_6_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_15.unity", "scenebasics/scene_basic_6_15", "Scene_Basic_6_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_16.unity", "scenebasics/scene_basic_6_16", "Scene_Basic_6_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_6_17.unity", "scenebasics/scene_basic_6_17", "Scene_Basic_6_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_0.unity", "scenebasics/scene_basic_7_0", "Scene_Basic_7_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_1.unity", "scenebasics/scene_basic_7_1", "Scene_Basic_7_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_2.unity", "scenebasics/scene_basic_7_2", "Scene_Basic_7_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_3.unity", "scenebasics/scene_basic_7_3", "Scene_Basic_7_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_4.unity", "scenebasics/scene_basic_7_4", "Scene_Basic_7_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_5.unity", "scenebasics/scene_basic_7_5", "Scene_Basic_7_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_6.unity", "scenebasics/scene_basic_7_6", "Scene_Basic_7_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_7.unity", "scenebasics/scene_basic_7_7", "Scene_Basic_7_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_8.unity", "scenebasics/scene_basic_7_8", "Scene_Basic_7_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_9.unity", "scenebasics/scene_basic_7_9", "Scene_Basic_7_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_10.unity", "scenebasics/scene_basic_7_10", "Scene_Basic_7_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_11.unity", "scenebasics/scene_basic_7_11", "Scene_Basic_7_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_12.unity", "scenebasics/scene_basic_7_12", "Scene_Basic_7_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_13.unity", "scenebasics/scene_basic_7_13", "Scene_Basic_7_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_14.unity", "scenebasics/scene_basic_7_14", "Scene_Basic_7_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_15.unity", "scenebasics/scene_basic_7_15", "Scene_Basic_7_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_16.unity", "scenebasics/scene_basic_7_16", "Scene_Basic_7_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_7_17.unity", "scenebasics/scene_basic_7_17", "Scene_Basic_7_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_0.unity", "scenebasics/scene_basic_8_0", "Scene_Basic_8_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_1.unity", "scenebasics/scene_basic_8_1", "Scene_Basic_8_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_2.unity", "scenebasics/scene_basic_8_2", "Scene_Basic_8_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_3.unity", "scenebasics/scene_basic_8_3", "Scene_Basic_8_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_4.unity", "scenebasics/scene_basic_8_4", "Scene_Basic_8_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_5.unity", "scenebasics/scene_basic_8_5", "Scene_Basic_8_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_6.unity", "scenebasics/scene_basic_8_6", "Scene_Basic_8_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_7.unity", "scenebasics/scene_basic_8_7", "Scene_Basic_8_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_8.unity", "scenebasics/scene_basic_8_8", "Scene_Basic_8_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_9.unity", "scenebasics/scene_basic_8_9", "Scene_Basic_8_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_10.unity", "scenebasics/scene_basic_8_10", "Scene_Basic_8_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_11.unity", "scenebasics/scene_basic_8_11", "Scene_Basic_8_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_12.unity", "scenebasics/scene_basic_8_12", "Scene_Basic_8_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_13.unity", "scenebasics/scene_basic_8_13", "Scene_Basic_8_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_14.unity", "scenebasics/scene_basic_8_14", "Scene_Basic_8_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_15.unity", "scenebasics/scene_basic_8_15", "Scene_Basic_8_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_16.unity", "scenebasics/scene_basic_8_16", "Scene_Basic_8_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_8_17.unity", "scenebasics/scene_basic_8_17", "Scene_Basic_8_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_0.unity", "scenebasics/scene_basic_9_0", "Scene_Basic_9_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_1.unity", "scenebasics/scene_basic_9_1", "Scene_Basic_9_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_2.unity", "scenebasics/scene_basic_9_2", "Scene_Basic_9_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_3.unity", "scenebasics/scene_basic_9_3", "Scene_Basic_9_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_4.unity", "scenebasics/scene_basic_9_4", "Scene_Basic_9_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_5.unity", "scenebasics/scene_basic_9_5", "Scene_Basic_9_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_6.unity", "scenebasics/scene_basic_9_6", "Scene_Basic_9_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_7.unity", "scenebasics/scene_basic_9_7", "Scene_Basic_9_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_8.unity", "scenebasics/scene_basic_9_8", "Scene_Basic_9_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_9.unity", "scenebasics/scene_basic_9_9", "Scene_Basic_9_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_10.unity", "scenebasics/scene_basic_9_10", "Scene_Basic_9_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_11.unity", "scenebasics/scene_basic_9_11", "Scene_Basic_9_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_12.unity", "scenebasics/scene_basic_9_12", "Scene_Basic_9_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_13.unity", "scenebasics/scene_basic_9_13", "Scene_Basic_9_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_14.unity", "scenebasics/scene_basic_9_14", "Scene_Basic_9_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_15.unity", "scenebasics/scene_basic_9_15", "Scene_Basic_9_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_16.unity", "scenebasics/scene_basic_9_16", "Scene_Basic_9_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_9_17.unity", "scenebasics/scene_basic_9_17", "Scene_Basic_9_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_0.unity", "scenebasics/scene_basic_10_0", "Scene_Basic_10_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_1.unity", "scenebasics/scene_basic_10_1", "Scene_Basic_10_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_2.unity", "scenebasics/scene_basic_10_2", "Scene_Basic_10_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_3.unity", "scenebasics/scene_basic_10_3", "Scene_Basic_10_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_4.unity", "scenebasics/scene_basic_10_4", "Scene_Basic_10_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_5.unity", "scenebasics/scene_basic_10_5", "Scene_Basic_10_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_6.unity", "scenebasics/scene_basic_10_6", "Scene_Basic_10_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_7.unity", "scenebasics/scene_basic_10_7", "Scene_Basic_10_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_8.unity", "scenebasics/scene_basic_10_8", "Scene_Basic_10_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_9.unity", "scenebasics/scene_basic_10_9", "Scene_Basic_10_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_10.unity", "scenebasics/scene_basic_10_10", "Scene_Basic_10_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_11.unity", "scenebasics/scene_basic_10_11", "Scene_Basic_10_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_12.unity", "scenebasics/scene_basic_10_12", "Scene_Basic_10_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_13.unity", "scenebasics/scene_basic_10_13", "Scene_Basic_10_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_14.unity", "scenebasics/scene_basic_10_14", "Scene_Basic_10_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_15.unity", "scenebasics/scene_basic_10_15", "Scene_Basic_10_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_16.unity", "scenebasics/scene_basic_10_16", "Scene_Basic_10_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_10_17.unity", "scenebasics/scene_basic_10_17", "Scene_Basic_10_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_0.unity", "scenebasics/scene_basic_11_0", "Scene_Basic_11_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_1.unity", "scenebasics/scene_basic_11_1", "Scene_Basic_11_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_2.unity", "scenebasics/scene_basic_11_2", "Scene_Basic_11_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_3.unity", "scenebasics/scene_basic_11_3", "Scene_Basic_11_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_4.unity", "scenebasics/scene_basic_11_4", "Scene_Basic_11_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_5.unity", "scenebasics/scene_basic_11_5", "Scene_Basic_11_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_6.unity", "scenebasics/scene_basic_11_6", "Scene_Basic_11_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_7.unity", "scenebasics/scene_basic_11_7", "Scene_Basic_11_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_8.unity", "scenebasics/scene_basic_11_8", "Scene_Basic_11_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_9.unity", "scenebasics/scene_basic_11_9", "Scene_Basic_11_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_10.unity", "scenebasics/scene_basic_11_10", "Scene_Basic_11_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_11.unity", "scenebasics/scene_basic_11_11", "Scene_Basic_11_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_12.unity", "scenebasics/scene_basic_11_12", "Scene_Basic_11_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_13.unity", "scenebasics/scene_basic_11_13", "Scene_Basic_11_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_14.unity", "scenebasics/scene_basic_11_14", "Scene_Basic_11_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_15.unity", "scenebasics/scene_basic_11_15", "Scene_Basic_11_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_16.unity", "scenebasics/scene_basic_11_16", "Scene_Basic_11_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_11_17.unity", "scenebasics/scene_basic_11_17", "Scene_Basic_11_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_0.unity", "scenebasics/scene_basic_12_0", "Scene_Basic_12_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_1.unity", "scenebasics/scene_basic_12_1", "Scene_Basic_12_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_2.unity", "scenebasics/scene_basic_12_2", "Scene_Basic_12_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_3.unity", "scenebasics/scene_basic_12_3", "Scene_Basic_12_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_4.unity", "scenebasics/scene_basic_12_4", "Scene_Basic_12_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_5.unity", "scenebasics/scene_basic_12_5", "Scene_Basic_12_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_6.unity", "scenebasics/scene_basic_12_6", "Scene_Basic_12_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_7.unity", "scenebasics/scene_basic_12_7", "Scene_Basic_12_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_8.unity", "scenebasics/scene_basic_12_8", "Scene_Basic_12_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_9.unity", "scenebasics/scene_basic_12_9", "Scene_Basic_12_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_10.unity", "scenebasics/scene_basic_12_10", "Scene_Basic_12_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_11.unity", "scenebasics/scene_basic_12_11", "Scene_Basic_12_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_12.unity", "scenebasics/scene_basic_12_12", "Scene_Basic_12_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_13.unity", "scenebasics/scene_basic_12_13", "Scene_Basic_12_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_14.unity", "scenebasics/scene_basic_12_14", "Scene_Basic_12_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_15.unity", "scenebasics/scene_basic_12_15", "Scene_Basic_12_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_16.unity", "scenebasics/scene_basic_12_16", "Scene_Basic_12_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_12_17.unity", "scenebasics/scene_basic_12_17", "Scene_Basic_12_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_0.unity", "scenebasics/scene_basic_13_0", "Scene_Basic_13_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_1.unity", "scenebasics/scene_basic_13_1", "Scene_Basic_13_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_2.unity", "scenebasics/scene_basic_13_2", "Scene_Basic_13_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_3.unity", "scenebasics/scene_basic_13_3", "Scene_Basic_13_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_4.unity", "scenebasics/scene_basic_13_4", "Scene_Basic_13_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_5.unity", "scenebasics/scene_basic_13_5", "Scene_Basic_13_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_6.unity", "scenebasics/scene_basic_13_6", "Scene_Basic_13_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_7.unity", "scenebasics/scene_basic_13_7", "Scene_Basic_13_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_8.unity", "scenebasics/scene_basic_13_8", "Scene_Basic_13_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_9.unity", "scenebasics/scene_basic_13_9", "Scene_Basic_13_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_10.unity", "scenebasics/scene_basic_13_10", "Scene_Basic_13_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_11.unity", "scenebasics/scene_basic_13_11", "Scene_Basic_13_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_12.unity", "scenebasics/scene_basic_13_12", "Scene_Basic_13_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_13.unity", "scenebasics/scene_basic_13_13", "Scene_Basic_13_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_14.unity", "scenebasics/scene_basic_13_14", "Scene_Basic_13_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_15.unity", "scenebasics/scene_basic_13_15", "Scene_Basic_13_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_16.unity", "scenebasics/scene_basic_13_16", "Scene_Basic_13_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_13_17.unity", "scenebasics/scene_basic_13_17", "Scene_Basic_13_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_0.unity", "scenebasics/scene_basic_14_0", "Scene_Basic_14_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_1.unity", "scenebasics/scene_basic_14_1", "Scene_Basic_14_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_2.unity", "scenebasics/scene_basic_14_2", "Scene_Basic_14_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_3.unity", "scenebasics/scene_basic_14_3", "Scene_Basic_14_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_4.unity", "scenebasics/scene_basic_14_4", "Scene_Basic_14_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_5.unity", "scenebasics/scene_basic_14_5", "Scene_Basic_14_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_6.unity", "scenebasics/scene_basic_14_6", "Scene_Basic_14_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_7.unity", "scenebasics/scene_basic_14_7", "Scene_Basic_14_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_8.unity", "scenebasics/scene_basic_14_8", "Scene_Basic_14_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_9.unity", "scenebasics/scene_basic_14_9", "Scene_Basic_14_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_10.unity", "scenebasics/scene_basic_14_10", "Scene_Basic_14_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_11.unity", "scenebasics/scene_basic_14_11", "Scene_Basic_14_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_12.unity", "scenebasics/scene_basic_14_12", "Scene_Basic_14_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_13.unity", "scenebasics/scene_basic_14_13", "Scene_Basic_14_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_14.unity", "scenebasics/scene_basic_14_14", "Scene_Basic_14_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_15.unity", "scenebasics/scene_basic_14_15", "Scene_Basic_14_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_16.unity", "scenebasics/scene_basic_14_16", "Scene_Basic_14_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_14_17.unity", "scenebasics/scene_basic_14_17", "Scene_Basic_14_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_0.unity", "scenebasics/scene_basic_15_0", "Scene_Basic_15_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_1.unity", "scenebasics/scene_basic_15_1", "Scene_Basic_15_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_2.unity", "scenebasics/scene_basic_15_2", "Scene_Basic_15_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_3.unity", "scenebasics/scene_basic_15_3", "Scene_Basic_15_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_4.unity", "scenebasics/scene_basic_15_4", "Scene_Basic_15_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_5.unity", "scenebasics/scene_basic_15_5", "Scene_Basic_15_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_6.unity", "scenebasics/scene_basic_15_6", "Scene_Basic_15_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_7.unity", "scenebasics/scene_basic_15_7", "Scene_Basic_15_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_8.unity", "scenebasics/scene_basic_15_8", "Scene_Basic_15_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_9.unity", "scenebasics/scene_basic_15_9", "Scene_Basic_15_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_10.unity", "scenebasics/scene_basic_15_10", "Scene_Basic_15_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_11.unity", "scenebasics/scene_basic_15_11", "Scene_Basic_15_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_12.unity", "scenebasics/scene_basic_15_12", "Scene_Basic_15_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_13.unity", "scenebasics/scene_basic_15_13", "Scene_Basic_15_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_14.unity", "scenebasics/scene_basic_15_14", "Scene_Basic_15_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_15.unity", "scenebasics/scene_basic_15_15", "Scene_Basic_15_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_16.unity", "scenebasics/scene_basic_15_16", "Scene_Basic_15_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_15_17.unity", "scenebasics/scene_basic_15_17", "Scene_Basic_15_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_0.unity", "scenebasics/scene_basic_16_0", "Scene_Basic_16_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_1.unity", "scenebasics/scene_basic_16_1", "Scene_Basic_16_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_2.unity", "scenebasics/scene_basic_16_2", "Scene_Basic_16_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_3.unity", "scenebasics/scene_basic_16_3", "Scene_Basic_16_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_4.unity", "scenebasics/scene_basic_16_4", "Scene_Basic_16_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_5.unity", "scenebasics/scene_basic_16_5", "Scene_Basic_16_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_6.unity", "scenebasics/scene_basic_16_6", "Scene_Basic_16_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_7.unity", "scenebasics/scene_basic_16_7", "Scene_Basic_16_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_8.unity", "scenebasics/scene_basic_16_8", "Scene_Basic_16_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_9.unity", "scenebasics/scene_basic_16_9", "Scene_Basic_16_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_10.unity", "scenebasics/scene_basic_16_10", "Scene_Basic_16_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_11.unity", "scenebasics/scene_basic_16_11", "Scene_Basic_16_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_12.unity", "scenebasics/scene_basic_16_12", "Scene_Basic_16_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_13.unity", "scenebasics/scene_basic_16_13", "Scene_Basic_16_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_14.unity", "scenebasics/scene_basic_16_14", "Scene_Basic_16_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_15.unity", "scenebasics/scene_basic_16_15", "Scene_Basic_16_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_16.unity", "scenebasics/scene_basic_16_16", "Scene_Basic_16_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_16_17.unity", "scenebasics/scene_basic_16_17", "Scene_Basic_16_17", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_0.unity", "scenebasics/scene_basic_17_0", "Scene_Basic_17_0", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_1.unity", "scenebasics/scene_basic_17_1", "Scene_Basic_17_1", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_2.unity", "scenebasics/scene_basic_17_2", "Scene_Basic_17_2", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_3.unity", "scenebasics/scene_basic_17_3", "Scene_Basic_17_3", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_4.unity", "scenebasics/scene_basic_17_4", "Scene_Basic_17_4", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_5.unity", "scenebasics/scene_basic_17_5", "Scene_Basic_17_5", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_6.unity", "scenebasics/scene_basic_17_6", "Scene_Basic_17_6", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_7.unity", "scenebasics/scene_basic_17_7", "Scene_Basic_17_7", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_8.unity", "scenebasics/scene_basic_17_8", "Scene_Basic_17_8", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_9.unity", "scenebasics/scene_basic_17_9", "Scene_Basic_17_9", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_10.unity", "scenebasics/scene_basic_17_10", "Scene_Basic_17_10", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_11.unity", "scenebasics/scene_basic_17_11", "Scene_Basic_17_11", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_12.unity", "scenebasics/scene_basic_17_12", "Scene_Basic_17_12", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_13.unity", "scenebasics/scene_basic_17_13", "Scene_Basic_17_13", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_14.unity", "scenebasics/scene_basic_17_14", "Scene_Basic_17_14", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_15.unity", "scenebasics/scene_basic_17_15", "Scene_Basic_17_15", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_16.unity", "scenebasics/scene_basic_17_16", "Scene_Basic_17_16", ".unity" },
    { "Assets/Game/Scenes/World/Scene_Basic_17_17.unity", "scenebasics/scene_basic_17_17", "Scene_Basic_17_17", ".unity" },
    { "Assets/Game/Scenes/OpenWorld.unity", "scenes", "OpenWorld", ".unity" },
    { "Assets/Game/Shaders/DistantSubstance.shader", "shaders", "DistantSubstance", ".shader" },
    { "Assets/Game/Shaders/Effect.shader", "shaders", "Effect", ".shader" },
    { "Assets/Game/Shaders/Preload.shadervariants", "shaders", "Preload", ".shadervariants" },
    { "Assets/Game/Shaders/ShaderLibrary/UnityUI.hlsl", "shaders", "UnityUI", ".hlsl" },
    { "Assets/Game/UIs/Animations/Foldable/d_fold.anim", "uis/animations", "d_fold", ".anim" },
    { "Assets/Game/UIs/Animations/Foldable/d_unfold.anim", "uis/animations", "d_unfold", ".anim" },
    { "Assets/Game/UIs/Animations/Foldable/d_unfold2fold.anim", "uis/animations", "d_unfold2fold", ".anim" },
    { "Assets/Game/UIs/Animations/Foldable/Foldable.controller", "uis/animations", "Foldable", ".controller" },
    { "Assets/Game/UIs/Animations/Hideable/FadeHide.anim", "uis/animations", "FadeHide", ".anim" },
    { "Assets/Game/UIs/Animations/Hideable/FadeShow.anim", "uis/animations", "FadeShow", ".anim" },
    { "Assets/Game/UIs/Animations/Hideable/Hideable.controller", "uis/animations", "Hideable", ".controller" },
    { "Assets/Game/UIs/Animations/Loopable/d_hide.anim", "uis/animations", "d_hide", ".anim" },
    { "Assets/Game/UIs/Animations/Loopable/d_loop.anim", "uis/animations", "d_loop", ".anim" },
    { "Assets/Game/UIs/Animations/Loopable/d_show.anim", "uis/animations", "d_show", ".anim" },
    { "Assets/Game/UIs/Animations/Loopable/Loopable.controller", "uis/animations", "Loopable", ".controller" },
    { "Assets/Game/UIs/Fonts/en/Source/arial.ttf", "uis/fonts/en", "arial", ".ttf" },
    { "Assets/Game/UIs/Fonts/en/Source/georgia.ttf", "uis/fonts/en", "georgia", ".ttf" },
    { "Assets/Game/UIs/Fonts/en/Source/Readme.txt", "uis/fonts/en", "Readme", ".txt" },
    { "Assets/Game/UIs/Fonts/en/Text SDF Default.mat", "uis/fonts/en", "Text SDF Default", ".mat" },
    { "Assets/Game/UIs/Fonts/en/Text SDF Outline Blue.mat", "uis/fonts/en", "Text SDF Outline Blue", ".mat" },
    { "Assets/Game/UIs/Fonts/en/Text SDF.asset", "uis/fonts/en", "Text SDF", ".asset" },
    { "Assets/Game/UIs/Fonts/en/Title SDF Outline Blue.mat", "uis/fonts/en", "Title SDF Outline Blue", ".mat" },
    { "Assets/Game/UIs/Fonts/en/Title SDF Outline Brown.mat", "uis/fonts/en", "Title SDF Outline Brown", ".mat" },
    { "Assets/Game/UIs/Fonts/en/Title SDF Outline White.mat", "uis/fonts/en", "Title SDF Outline White", ".mat" },
    { "Assets/Game/UIs/Fonts/en/Title SDF System.mat", "uis/fonts/en", "Title SDF System", ".mat" },
    { "Assets/Game/UIs/Fonts/en/Title SDF.asset", "uis/fonts/en", "Title SDF", ".asset" },
    { "Assets/Game/UIs/Fonts/Gradient Blue.asset", "uis/fonts/shared", "Gradient Blue", ".asset" },
    { "Assets/Game/UIs/Fonts/Gradient Brown.asset", "uis/fonts/shared", "Gradient Brown", ".asset" },
    { "Assets/Game/UIs/Fonts/Gradient Yellow.asset", "uis/fonts/shared", "Gradient Yellow", ".asset" },
    { "Assets/Game/UIs/Fonts/Text SDF Outline Black.asset", "uis/fonts/shared", "Text SDF Outline Black", ".asset" },
    { "Assets/Game/UIs/Fonts/Text TTF.asset", "uis/fonts/shared", "Text TTF", ".asset" },
    { "Assets/Game/UIs/Fonts/Title SDF Outline Blue.asset", "uis/fonts/shared", "Title SDF Outline Blue", ".asset" },
    { "Assets/Game/UIs/Fonts/Title SDF Outline Brown.asset", "uis/fonts/shared", "Title SDF Outline Brown", ".asset" },
    { "Assets/Game/UIs/Fonts/Title SDF Outline White.asset", "uis/fonts/shared", "Title SDF Outline White", ".asset" },
    { "Assets/Game/UIs/Fonts/zh/Source/Font FZCSJW.TTF", "uis/fonts/zh", "Font FZCSJW", ".TTF" },
    { "Assets/Game/UIs/Fonts/zh/Source/Font SIMHEI.TTF", "uis/fonts/zh", "Font SIMHEI", ".TTF" },
    { "Assets/Game/UIs/Fonts/zh/Source/Readme.txt", "uis/fonts/zh", "Readme", ".txt" },
    { "Assets/Game/UIs/Fonts/zh/Source/Text List.txt", "uis/fonts/zh", "Text List", ".txt" },
    { "Assets/Game/UIs/Fonts/zh/Source/Title List.txt", "uis/fonts/zh", "Title List", ".txt" },
    { "Assets/Game/UIs/Fonts/zh/Text SDF Default.mat", "uis/fonts/zh", "Text SDF Default", ".mat" },
    { "Assets/Game/UIs/Fonts/zh/Text SDF Outline Blue.mat", "uis/fonts/zh", "Text SDF Outline Blue", ".mat" },
    { "Assets/Game/UIs/Fonts/zh/Text SDF.asset", "uis/fonts/zh", "Text SDF", ".asset" },
    { "Assets/Game/UIs/Fonts/zh/Title SDF Outline Blue.mat", "uis/fonts/zh", "Title SDF Outline Blue", ".mat" },
    { "Assets/Game/UIs/Fonts/zh/Title SDF Outline Brown.mat", "uis/fonts/zh", "Title SDF Outline Brown", ".mat" },
    { "Assets/Game/UIs/Fonts/zh/Title SDF Outline White.mat", "uis/fonts/zh", "Title SDF Outline White", ".mat" },
    { "Assets/Game/UIs/Fonts/zh/Title SDF System.mat", "uis/fonts/zh", "Title SDF System", ".mat" },
    { "Assets/Game/UIs/Fonts/zh/Title SDF.asset", "uis/fonts/zh", "Title SDF", ".asset" },
    { "Assets/Game/UIs/Fonts/zh_TW/Source/Font FZCSJW.TTF", "uis/fonts/zh_tw", "Font FZCSJW", ".TTF" },
    { "Assets/Game/UIs/Fonts/zh_TW/Source/Font SIMHEI.TTF", "uis/fonts/zh_tw", "Font SIMHEI", ".TTF" },
    { "Assets/Game/UIs/Fonts/zh_TW/Source/Readme.txt", "uis/fonts/zh_tw", "Readme", ".txt" },
    { "Assets/Game/UIs/Fonts/zh_TW/Source/Text List.txt", "uis/fonts/zh_tw", "Text List", ".txt" },
    { "Assets/Game/UIs/Fonts/zh_TW/Source/Title List.txt", "uis/fonts/zh_tw", "Title List", ".txt" },
    { "Assets/Game/UIs/Fonts/zh_TW/Text SDF Default.mat", "uis/fonts/zh_tw", "Text SDF Default", ".mat" },
    { "Assets/Game/UIs/Fonts/zh_TW/Text SDF Outline Blue.mat", "uis/fonts/zh_tw", "Text SDF Outline Blue", ".mat" },
    { "Assets/Game/UIs/Fonts/zh_TW/Text SDF.asset", "uis/fonts/zh_tw", "Text SDF", ".asset" },
    { "Assets/Game/UIs/Fonts/zh_TW/Title SDF Outline Blue.mat", "uis/fonts/zh_tw", "Title SDF Outline Blue", ".mat" },
    { "Assets/Game/UIs/Fonts/zh_TW/Title SDF Outline Brown.mat", "uis/fonts/zh_tw", "Title SDF Outline Brown", ".mat" },
    { "Assets/Game/UIs/Fonts/zh_TW/Title SDF Outline White.mat", "uis/fonts/zh_tw", "Title SDF Outline White", ".mat" },
    { "Assets/Game/UIs/Fonts/zh_TW/Title SDF System.mat", "uis/fonts/zh_tw", "Title SDF System", ".mat" },
    { "Assets/Game/UIs/Fonts/zh_TW/Title SDF.asset", "uis/fonts/zh_tw", "Title SDF", ".asset" },
    { "Assets/Game/UIs/Images/LoadingTips/bg_034.png", "uis/images/loadingtips", "bg_034", ".png" },
    { "Assets/Game/UIs/Images/LoadingTips/light_05.png", "uis/images/loadingtips", "light_05", ".png" },
    { "Assets/Game/UIs/Images/LoadingTips/light_06.png", "uis/images/loadingtips", "light_06", ".png" },
    { "Assets/Game/UIs/Images/LoadingTips/LoadingTips.spriteatlas", "uis/images/loadingtips", "LoadingTips", ".spriteatlas" },
    { "Assets/Game/UIs/Images/Login/Ball_blue.png", "uis/images/login", "Ball_blue", ".png" },
    { "Assets/Game/UIs/Images/Login/Ball_gray.png", "uis/images/login", "Ball_gray", ".png" },
    { "Assets/Game/UIs/Images/Login/Ball_green.png", "uis/images/login", "Ball_green", ".png" },
    { "Assets/Game/UIs/Images/Login/Ball_red.png", "uis/images/login", "Ball_red", ".png" },
    { "Assets/Game/UIs/Images/Login/Ball_yellow.png", "uis/images/login", "Ball_yellow", ".png" },
    { "Assets/Game/UIs/Images/Login/Login.spriteatlas", "uis/images/login", "Login", ".spriteatlas" },
    { "Assets/Game/UIs/Images/Login/Tag_New.png", "uis/images/login", "Tag_New", ".png" },
    { "Assets/Game/UIs/Images/Login/ZoneFrame.png", "uis/images/login", "ZoneFrame", ".png" },
    { "Assets/Game/UIs/Images/Login/ZoneFrame_HL.png", "uis/images/login", "ZoneFrame_HL", ".png" },
    { "Assets/Game/UIs/Images/Login/ZoneSpliter.png", "uis/images/login", "ZoneSpliter", ".png" },
    { "Assets/Game/UIs/Images/Main/Icon_System_Settings.png", "uis/images/main", "Icon_System_Settings", ".png" },
    { "Assets/Game/UIs/Images/Main/IconFunction_Upgrade.png", "uis/images/main", "IconFunction_Upgrade", ".png" },
    { "Assets/Game/UIs/Images/Main/Joystick_Thumb.png", "uis/images/main", "Joystick_Thumb", ".png" },
    { "Assets/Game/UIs/Images/Main/Main.spriteatlas", "uis/images/main", "Main", ".spriteatlas" },
    { "Assets/Game/UIs/Images/Main/UI_Button_caokong_0.png", "uis/images/main", "UI_Button_caokong_0", ".png" },
    { "Assets/Game/UIs/Images/Main/UI_Button_caokong_1.png", "uis/images/main", "UI_Button_caokong_1", ".png" },
    { "Assets/Game/UIs/Images/Setting/IconMusic.png", "uis/images/setting", "IconMusic", ".png" },
    { "Assets/Game/UIs/Images/Setting/IconSFX.png", "uis/images/setting", "IconSFX", ".png" },
    { "Assets/Game/UIs/Images/Setting/ProgressThumb1.png", "uis/images/setting", "ProgressThumb1", ".png" },
    { "Assets/Game/UIs/Images/Setting/ProgressThumb2.png", "uis/images/setting", "ProgressThumb2", ".png" },
    { "Assets/Game/UIs/Images/Setting/QualityProgress.png", "uis/images/setting", "QualityProgress", ".png" },
    { "Assets/Game/UIs/Images/Setting/QualityProgressBG.png", "uis/images/setting", "QualityProgressBG", ".png" },
    { "Assets/Game/UIs/Images/Setting/Setting.spriteatlas", "uis/images/setting", "Setting", ".spriteatlas" },
    { "Assets/Game/UIs/Images/Setting/VolumeProgress.png", "uis/images/setting", "VolumeProgress", ".png" },
    { "Assets/Game/UIs/Images/Setting/VolumeProgressBG.png", "uis/images/setting", "VolumeProgressBG", ".png" },
    { "Assets/Game/UIs/Images/Shared/Button01.png", "uis/images/shared", "Button01", ".png" },
    { "Assets/Game/UIs/Images/Shared/Button03a.png", "uis/images/shared", "Button03a", ".png" },
    { "Assets/Game/UIs/Images/Shared/Button03b.png", "uis/images/shared", "Button03b", ".png" },
    { "Assets/Game/UIs/Images/Shared/ButtonClose01.png", "uis/images/shared", "ButtonClose01", ".png" },
    { "Assets/Game/UIs/Images/Shared/ButtonReturn01.png", "uis/images/shared", "ButtonReturn01", ".png" },
    { "Assets/Game/UIs/Images/Shared/Frame01.png", "uis/images/shared", "Frame01", ".png" },
    { "Assets/Game/UIs/Images/Shared/Frame02.png", "uis/images/shared", "Frame02", ".png" },
    { "Assets/Game/UIs/Images/Shared/Frame03.png", "uis/images/shared", "Frame03", ".png" },
    { "Assets/Game/UIs/Images/Shared/Frame04.png", "uis/images/shared", "Frame04", ".png" },
    { "Assets/Game/UIs/Images/Shared/Frame05.png", "uis/images/shared", "Frame05", ".png" },
    { "Assets/Game/UIs/Images/Shared/Frame06.png", "uis/images/shared", "Frame06", ".png" },
    { "Assets/Game/UIs/Images/Shared/Shared.spriteatlas", "uis/images/shared", "Shared", ".spriteatlas" },
    { "Assets/Game/UIs/Images/Shared/White.png", "uis/images/shared", "White", ".png" },
    { "Assets/Game/UIs/RawImages/loading_bg_1.jpg.bytes", "uis/rawimages/loading_bg_1.jpg", "loading_bg_1.jpg", ".bytes" },
    { "Assets/Game/UIs/RawImages/loading_bg_2.jpg.bytes", "uis/rawimages/loading_bg_2.jpg", "loading_bg_2.jpg", ".bytes" },
    { "Assets/Game/UIs/RawImages/loading_bg_3.jpg.bytes", "uis/rawimages/loading_bg_3.jpg", "loading_bg_3.jpg", ".bytes" },
    { "Assets/Game/UIs/RawImages/loading_bg_4.jpg.bytes", "uis/rawimages/loading_bg_4.jpg", "loading_bg_4.jpg", ".bytes" },
    { "Assets/Game/UIs/RawImages/Quality_Fast.jpg.bytes", "uis/rawimages/quality_fast.jpg", "Quality_Fast.jpg", ".bytes" },
    { "Assets/Game/UIs/RawImages/Quality_Good.jpg.bytes", "uis/rawimages/quality_good.jpg", "Quality_Good.jpg", ".bytes" },
    { "Assets/Game/UIs/RawImages/Quality_Normal.jpg.bytes", "uis/rawimages/quality_normal.jpg", "Quality_Normal.jpg", ".bytes" },
    { "Assets/Game/UIs/RawImages/Quality_Perfect.jpg.bytes", "uis/rawimages/quality_perfect.jpg", "Quality_Perfect.jpg", ".bytes" },
    { "Assets/Game/UIs/Tips/DisconnectTips/DisconnectedTip.prefab", "uis/tips/disconnecttips", "DisconnectedTip", ".prefab" },
    { "Assets/Game/UIs/Tips/LoadingTips/Animation/Hide.anim", "uis/tips/loadingtips", "Hide", ".anim" },
    { "Assets/Game/UIs/Tips/LoadingTips/Animation/LoadingTip.controller", "uis/tips/loadingtips", "LoadingTip", ".controller" },
    { "Assets/Game/UIs/Tips/LoadingTips/Animation/Loop.anim", "uis/tips/loadingtips", "Loop", ".anim" },
    { "Assets/Game/UIs/Tips/LoadingTips/Animation/Pending.anim", "uis/tips/loadingtips", "Pending", ".anim" },
    { "Assets/Game/UIs/Tips/LoadingTips/Animation/Show.anim", "uis/tips/loadingtips", "Show", ".anim" },
    { "Assets/Game/UIs/Tips/LoadingTips/LoadingTip.prefab", "uis/tips/loadingtips", "LoadingTip", ".prefab" },
    { "Assets/Game/UIs/Tips/MessageBox/MessageBox.prefab", "uis/tips/messagebox", "MessageBox", ".prefab" },
    { "Assets/Game/UIs/Views/Channels/dev/LoginAgentView.prefab", "uis/views/channels", "LoginAgentView", ".prefab" },
    { "Assets/Game/UIs/Views/Loading/Animations/Hide.anim", "uis/views/loading", "Hide", ".anim" },
    { "Assets/Game/UIs/Views/Loading/Animations/Hideable.overrideController", "uis/views/loading", "Hideable", ".overrideController" },
    { "Assets/Game/UIs/Views/Loading/Animations/Show.anim", "uis/views/loading", "Show", ".anim" },
    { "Assets/Game/UIs/Views/Loading/LoadingTest.lua", "uis/views/loading", "LoadingTest", ".lua" },
    { "Assets/Game/UIs/Views/Loading/LoadingView.prefab", "uis/views/loading", "LoadingView", ".prefab" },
    { "Assets/Game/UIs/Views/Login/Animations/ZoneHide.anim", "uis/views/login", "ZoneHide", ".anim" },
    { "Assets/Game/UIs/Views/Login/Animations/ZoneShow.anim", "uis/views/login", "ZoneShow", ".anim" },
    { "Assets/Game/UIs/Views/Login/Animations/ZoneView.overrideController", "uis/views/login", "ZoneView", ".overrideController" },
    { "Assets/Game/UIs/Views/Login/LoginView.prefab", "uis/views/login", "LoginView", ".prefab" },
    { "Assets/Game/UIs/Views/Login/LoginViewTest.lua", "uis/views/login", "LoginViewTest", ".lua" },
    { "Assets/Game/UIs/Views/Login/ZoneGroupItem.prefab", "uis/views/login", "ZoneGroupItem", ".prefab" },
    { "Assets/Game/UIs/Views/Login/ZoneItem.prefab", "uis/views/login", "ZoneItem", ".prefab" },
    { "Assets/Game/UIs/Views/Login/ZoneView.prefab", "uis/views/login", "ZoneView", ".prefab" },
    { "Assets/Game/UIs/Views/Main/arrow.png", "uis/views/main", "arrow", ".png" },
    { "Assets/Game/UIs/Views/Main/Joystick.prefab", "uis/views/main", "Joystick", ".prefab" },
    { "Assets/Game/UIs/Views/Main/MainView.prefab", "uis/views/main", "MainView", ".prefab" },
    { "Assets/Game/UIs/Views/Setting/SettingView.prefab", "uis/views/setting", "SettingView", ".prefab" },
}

-- 根据字段名查询
local find_by_field = function(row, key)
    local i = fields[key]
    if i then
        return row[i]
    else
        i = refs[key]
        if i then
            return assets[key](row[i])
        else
            return nil
        end
    end
end

-- meta
local meta = { __index = find_by_field }
for i = 1, 555 do
    setmetatable(datas[i], meta)
end

-- 初始化索引
local rows_to_table = function(...)
    local indexes = { ... }
    local top = {}
    for i, row in ipairs(datas) do
        local current = top
        for j, index in ipairs(indexes) do
            local value = row[fields[index]]
            if (j < #indexes) then
                local sub = current[value]
                if (not (sub)) then
                    sub = {}
                    current[value] = sub
                end
                current = sub
            else
                current[value] = row
            end
        end
    end
    return top
end

-- 主键映射
local pool_id = rows_to_table("id")

-- 查询所有数据
function assets.all()
    return datas
end

-- 根据主键查询数据
function assets.get(id)
    return pool_id[id]
end

return assets
